// Import Module Configurations

import { ImportModuleConfig, ImportFieldConfig } from './types';

// Members Module Configuration
export const membersConfig: ImportModuleConfig = {
  module: 'members',
  displayName: 'Members',
  description: 'Import gym members with their contact information and membership details',
  tableName: 'profiles',
  duplicateKeys: ['email'],
  duplicateDisplayField: 'email',
  templateFileName: 'members_import_template.csv',
  fields: [
    {
      name: 'email',
      label: 'Email Address',
      type: 'email',
      required: true,
      description: 'Primary email address for the member',
      examples: ['john.doe@example.com', 'jane.smith@gym.com'],
    },
    {
      name: 'first_name',
      label: 'First Name',
      type: 'string',
      required: true,
      description: 'Member\'s first name',
      examples: ['John', 'Jane'],
    },
    {
      name: 'last_name',
      label: 'Last Name',
      type: 'string',
      required: true,
      description: 'Member\'s last name',
      examples: ['Doe', 'Smith'],
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'phone',
      description: 'Contact phone number',
      examples: ['(555) 123-4567', '+1-555-987-6543'],
    },
    {
      name: 'date_of_birth',
      label: 'Date of Birth',
      type: 'date',
      description: 'Member\'s birth date (YYYY-MM-DD)',
      examples: ['1990-05-15', '1985-12-01'],
    },
    {
      name: 'gender',
      label: 'Gender',
      type: 'enum',
      enumValues: ['male', 'female', 'other', 'prefer_not_to_say'],
      description: 'Member\'s gender',
      examples: ['male', 'female'],
    },
    {
      name: 'address',
      label: 'Street Address',
      type: 'string',
      description: 'Street address',
      examples: ['123 Main St', '456 Oak Ave Apt 2B'],
    },
    {
      name: 'city',
      label: 'City',
      type: 'string',
      description: 'City name',
      examples: ['New York', 'Los Angeles'],
    },
    {
      name: 'state',
      label: 'State/Province',
      type: 'string',
      description: 'State or province code',
      examples: ['NY', 'CA', 'TX'],
    },
    {
      name: 'zip_code',
      label: 'ZIP/Postal Code',
      type: 'string',
      description: 'Postal code',
      examples: ['10001', '90210'],
    },
    {
      name: 'emergency_contact_name',
      label: 'Emergency Contact Name',
      type: 'string',
      description: 'Name of emergency contact',
      examples: ['Mary Doe', 'Bob Smith'],
    },
    {
      name: 'emergency_contact_phone',
      label: 'Emergency Contact Phone',
      type: 'phone',
      description: 'Emergency contact phone number',
      examples: ['(555) 111-2222'],
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'string',
      description: 'Additional notes about the member',
      examples: ['Prefers morning classes', 'Medical condition: asthma'],
    },
    {
      name: 'membership_type',
      label: 'Membership Type',
      type: 'string',
      description: 'Type of membership plan (will be matched to existing plans)',
      examples: ['Monthly Premium', 'Annual Basic', 'Student Plan'],
    },
    {
      name: 'membership_start_date',
      label: 'Membership Start Date',
      type: 'date',
      description: 'When membership starts (YYYY-MM-DD)',
      examples: ['2024-01-01', '2024-06-15'],
    },
    {
      name: 'membership_status',
      label: 'Membership Status',
      type: 'enum',
      enumValues: ['active', 'inactive', 'frozen', 'cancelled', 'past_due'],
      description: 'Current membership status',
      examples: ['active', 'frozen'],
      defaultValue: 'active',
    },
  ],
};

// Classes Module Configuration
export const classesConfig: ImportModuleConfig = {
  module: 'classes',
  displayName: 'Classes',
  description: 'Import class schedules and recurring class templates',
  tableName: 'classes',
  duplicateKeys: ['name', 'scheduled_at'],
  duplicateDisplayField: 'name',
  templateFileName: 'classes_import_template.csv',
  fields: [
    {
      name: 'name',
      label: 'Class Name',
      type: 'string',
      required: true,
      description: 'Name of the class',
      examples: ['Morning Yoga', 'HIIT Bootcamp', 'Spin Class'],
    },
    {
      name: 'description',
      label: 'Description',
      type: 'string',
      description: 'Class description',
      examples: ['A relaxing yoga session to start your day'],
    },
    {
      name: 'category',
      label: 'Category',
      type: 'string',
      description: 'Class category (will be matched or created)',
      examples: ['Yoga', 'Cardio', 'Strength', 'Dance'],
    },
    {
      name: 'instructor_email',
      label: 'Instructor Email',
      type: 'email',
      description: 'Email of the instructor (must exist in system)',
      examples: ['trainer@gym.com'],
    },
    {
      name: 'instructor_name',
      label: 'Instructor Name',
      type: 'string',
      description: 'Instructor name (alternative to email)',
      examples: ['John Trainer', 'Sarah Coach'],
    },
    {
      name: 'duration_minutes',
      label: 'Duration (minutes)',
      type: 'number',
      required: true,
      description: 'Class duration in minutes',
      examples: ['45', '60', '90'],
      defaultValue: 60,
    },
    {
      name: 'max_capacity',
      label: 'Maximum Capacity',
      type: 'number',
      required: true,
      description: 'Maximum number of participants',
      examples: ['15', '20', '30'],
      defaultValue: 20,
    },
    {
      name: 'scheduled_date',
      label: 'Date',
      type: 'date',
      required: true,
      description: 'Class date (YYYY-MM-DD)',
      examples: ['2024-01-15', '2024-02-01'],
    },
    {
      name: 'start_time',
      label: 'Start Time',
      type: 'string',
      required: true,
      description: 'Class start time (HH:MM in 24h format)',
      examples: ['09:00', '14:30', '18:00'],
    },
    {
      name: 'location',
      label: 'Location/Room',
      type: 'string',
      description: 'Room or location name',
      examples: ['Studio A', 'Main Gym', 'Pool Area'],
    },
    {
      name: 'is_recurring',
      label: 'Recurring',
      type: 'boolean',
      description: 'Whether this is a recurring class template',
      examples: ['true', 'false', 'yes', 'no'],
      defaultValue: false,
    },
    {
      name: 'recurrence_days',
      label: 'Recurrence Days',
      type: 'string',
      description: 'Days of week for recurring classes (comma-separated)',
      examples: ['Monday,Wednesday,Friday', 'Tuesday,Thursday'],
    },
    {
      name: 'difficulty_level',
      label: 'Difficulty Level',
      type: 'enum',
      enumValues: ['beginner', 'intermediate', 'advanced', 'all_levels'],
      description: 'Class difficulty level',
      examples: ['beginner', 'intermediate'],
      defaultValue: 'all_levels',
    },
  ],
};

// Staff Module Configuration
export const staffConfig: ImportModuleConfig = {
  module: 'staff',
  displayName: 'Staff & Trainers',
  description: 'Import staff members, trainers, and their certifications',
  tableName: 'profiles',
  duplicateKeys: ['email'],
  duplicateDisplayField: 'email',
  templateFileName: 'staff_import_template.csv',
  fields: [
    {
      name: 'email',
      label: 'Email Address',
      type: 'email',
      required: true,
      description: 'Staff member\'s email address',
      examples: ['trainer@gym.com', 'manager@fitness.com'],
    },
    {
      name: 'first_name',
      label: 'First Name',
      type: 'string',
      required: true,
      description: 'Staff member\'s first name',
      examples: ['Mike', 'Sarah'],
    },
    {
      name: 'last_name',
      label: 'Last Name',
      type: 'string',
      required: true,
      description: 'Staff member\'s last name',
      examples: ['Johnson', 'Williams'],
    },
    {
      name: 'role',
      label: 'Role',
      type: 'enum',
      required: true,
      enumValues: ['manager', 'staff', 'trainer'],
      description: 'Staff role in the system',
      examples: ['trainer', 'staff', 'manager'],
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'phone',
      description: 'Contact phone number',
      examples: ['(555) 123-4567'],
    },
    {
      name: 'department',
      label: 'Department',
      type: 'string',
      description: 'Department assignment',
      examples: ['Personal Training', 'Front Desk', 'Management', 'Maintenance'],
    },
    {
      name: 'position',
      label: 'Position/Title',
      type: 'string',
      description: 'Job title or position',
      examples: ['Senior Trainer', 'Fitness Instructor', 'Operations Manager'],
    },
    {
      name: 'hire_date',
      label: 'Hire Date',
      type: 'date',
      description: 'Date of hire (YYYY-MM-DD)',
      examples: ['2023-01-15', '2022-06-01'],
    },
    {
      name: 'hourly_rate',
      label: 'Hourly Rate',
      type: 'currency',
      description: 'Hourly pay rate',
      examples: ['25.00', '35.50'],
    },
    {
      name: 'certifications',
      label: 'Certifications',
      type: 'string',
      description: 'Certifications held (comma-separated)',
      examples: ['CPR, ACE Personal Trainer', 'NASM-CPT, Yoga Alliance RYT-200'],
    },
    {
      name: 'specialties',
      label: 'Specialties',
      type: 'string',
      description: 'Training specialties (comma-separated)',
      examples: ['Weight Loss, Strength Training', 'Yoga, Pilates, Stretching'],
    },
    {
      name: 'bio',
      label: 'Bio/Description',
      type: 'string',
      description: 'Staff member bio for member-facing profiles',
      examples: ['10 years experience in personal training...'],
    },
    {
      name: 'emergency_contact_name',
      label: 'Emergency Contact Name',
      type: 'string',
      description: 'Emergency contact name',
      examples: ['Jane Johnson'],
    },
    {
      name: 'emergency_contact_phone',
      label: 'Emergency Contact Phone',
      type: 'phone',
      description: 'Emergency contact phone',
      examples: ['(555) 999-8888'],
    },
  ],
};

// Equipment Module Configuration
export const equipmentConfig: ImportModuleConfig = {
  module: 'equipment',
  displayName: 'Equipment',
  description: 'Import gym equipment inventory with maintenance tracking',
  tableName: 'equipment',
  duplicateKeys: ['serial_number'],
  duplicateDisplayField: 'name',
  templateFileName: 'equipment_import_template.csv',
  fields: [
    {
      name: 'name',
      label: 'Equipment Name',
      type: 'string',
      required: true,
      description: 'Name of the equipment',
      examples: ['Treadmill Pro 5000', 'Olympic Barbell', 'Rowing Machine'],
    },
    {
      name: 'equipment_type',
      label: 'Type',
      type: 'enum',
      required: true,
      enumValues: ['cardio', 'strength', 'functional', 'other'],
      description: 'Equipment category',
      examples: ['cardio', 'strength'],
    },
    {
      name: 'brand',
      label: 'Brand',
      type: 'string',
      description: 'Manufacturer/Brand name',
      examples: ['Life Fitness', 'Hammer Strength', 'Rogue'],
    },
    {
      name: 'model',
      label: 'Model',
      type: 'string',
      description: 'Model number or name',
      examples: ['95T Elevation', 'HD Elite', 'Echo Bike'],
    },
    {
      name: 'serial_number',
      label: 'Serial Number',
      type: 'string',
      description: 'Unique serial number',
      examples: ['SN-2024-001', 'LF95T-12345'],
    },
    {
      name: 'purchase_date',
      label: 'Purchase Date',
      type: 'date',
      description: 'Date of purchase (YYYY-MM-DD)',
      examples: ['2023-06-15', '2024-01-01'],
    },
    {
      name: 'purchase_price',
      label: 'Purchase Price',
      type: 'currency',
      description: 'Original purchase price',
      examples: ['4999.99', '299.00'],
    },
    {
      name: 'warranty_expiry',
      label: 'Warranty Expiry Date',
      type: 'date',
      description: 'Warranty expiration date (YYYY-MM-DD)',
      examples: ['2026-06-15', '2025-12-31'],
    },
    {
      name: 'location',
      label: 'Location',
      type: 'string',
      description: 'Where equipment is located',
      examples: ['Main Floor', 'Cardio Room', 'Free Weight Area'],
    },
    {
      name: 'status',
      label: 'Status',
      type: 'enum',
      enumValues: ['active', 'maintenance', 'out_of_service', 'retired'],
      description: 'Current equipment status',
      examples: ['active', 'maintenance'],
      defaultValue: 'active',
    },
    {
      name: 'last_maintenance_date',
      label: 'Last Maintenance Date',
      type: 'date',
      description: 'Date of last maintenance (YYYY-MM-DD)',
      examples: ['2024-01-15'],
    },
    {
      name: 'maintenance_interval_days',
      label: 'Maintenance Interval (days)',
      type: 'number',
      description: 'Days between scheduled maintenance',
      examples: ['30', '90', '180'],
      defaultValue: 90,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'string',
      description: 'Additional notes or specifications',
      examples: ['Requires calibration monthly', 'Belt replaced 2024-01-01'],
    },
  ],
};

// Memberships/Plans Module Configuration
export const membershipsConfig: ImportModuleConfig = {
  module: 'memberships',
  displayName: 'Membership Plans',
  description: 'Import membership plan definitions and pricing',
  tableName: 'membership_plans',
  duplicateKeys: ['name'],
  duplicateDisplayField: 'name',
  templateFileName: 'memberships_import_template.csv',
  fields: [
    {
      name: 'name',
      label: 'Plan Name',
      type: 'string',
      required: true,
      description: 'Name of the membership plan',
      examples: ['Monthly Basic', 'Annual Premium', 'Student Discount'],
    },
    {
      name: 'description',
      label: 'Description',
      type: 'string',
      description: 'Plan description',
      examples: ['Full access to all facilities and classes'],
    },
    {
      name: 'price',
      label: 'Price',
      type: 'currency',
      required: true,
      description: 'Monthly or period price',
      examples: ['49.99', '99.00', '499.00'],
    },
    {
      name: 'billing_period',
      label: 'Billing Period',
      type: 'enum',
      enumValues: ['monthly', 'quarterly', 'annual', 'one_time'],
      description: 'How often the plan is billed',
      examples: ['monthly', 'annual'],
      defaultValue: 'monthly',
    },
    {
      name: 'duration_months',
      label: 'Duration (months)',
      type: 'number',
      description: 'Contract duration in months (0 for month-to-month)',
      examples: ['0', '12', '6'],
      defaultValue: 0,
    },
    {
      name: 'setup_fee',
      label: 'Setup/Enrollment Fee',
      type: 'currency',
      description: 'One-time enrollment fee',
      examples: ['0', '49.99', '99.00'],
      defaultValue: '0',
    },
    {
      name: 'class_access',
      label: 'Class Access',
      type: 'enum',
      enumValues: ['none', 'limited', 'unlimited'],
      description: 'Level of class access included',
      examples: ['unlimited', 'limited'],
      defaultValue: 'unlimited',
    },
    {
      name: 'guest_passes',
      label: 'Guest Passes',
      type: 'number',
      description: 'Number of monthly guest passes included',
      examples: ['0', '2', '5'],
      defaultValue: 0,
    },
    {
      name: 'trainer_sessions',
      label: 'Trainer Sessions Included',
      type: 'number',
      description: 'Number of personal training sessions included',
      examples: ['0', '2', '4'],
      defaultValue: 0,
    },
    {
      name: 'is_active',
      label: 'Active',
      type: 'boolean',
      description: 'Whether plan is currently available for purchase',
      examples: ['true', 'false'],
      defaultValue: true,
    },
    {
      name: 'features',
      label: 'Features',
      type: 'string',
      description: 'Included features (comma-separated)',
      examples: ['24/7 Access, Locker Included, Towel Service'],
    },
  ],
};

// Expenses Module Configuration
export const expensesConfig: ImportModuleConfig = {
  module: 'expenses',
  displayName: 'Expenses',
  description: 'Import expense records for financial tracking',
  tableName: 'expenses',
  duplicateKeys: ['description', 'expense_date', 'amount'],
  duplicateDisplayField: 'description',
  templateFileName: 'expenses_import_template.csv',
  fields: [
    {
      name: 'description',
      label: 'Description',
      type: 'string',
      required: true,
      description: 'Expense description',
      examples: ['Office supplies', 'Equipment repair', 'Utilities - Electric'],
    },
    {
      name: 'amount',
      label: 'Amount',
      type: 'currency',
      required: true,
      description: 'Expense amount',
      examples: ['125.50', '1500.00'],
    },
    {
      name: 'expense_date',
      label: 'Expense Date',
      type: 'date',
      required: true,
      description: 'Date of expense (YYYY-MM-DD)',
      examples: ['2024-01-15', '2024-02-01'],
    },
    {
      name: 'category',
      label: 'Category',
      type: 'string',
      required: true,
      description: 'Expense category',
      examples: ['Utilities', 'Equipment', 'Marketing', 'Payroll', 'Supplies'],
    },
    {
      name: 'vendor',
      label: 'Vendor/Payee',
      type: 'string',
      description: 'Vendor or payee name',
      examples: ['ABC Equipment Co', 'City Water Utility'],
    },
    {
      name: 'payment_method',
      label: 'Payment Method',
      type: 'enum',
      enumValues: ['cash', 'check', 'credit_card', 'debit_card', 'bank_transfer', 'other'],
      description: 'How the expense was paid',
      examples: ['credit_card', 'check'],
      defaultValue: 'credit_card',
    },
    {
      name: 'payment_status',
      label: 'Payment Status',
      type: 'enum',
      enumValues: ['pending', 'paid', 'cancelled', 'refunded'],
      description: 'Current payment status',
      examples: ['paid', 'pending'],
      defaultValue: 'paid',
    },
    {
      name: 'reference_number',
      label: 'Reference Number',
      type: 'string',
      description: 'Invoice or reference number',
      examples: ['INV-2024-001', 'CHK-5523'],
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'string',
      description: 'Additional notes',
      examples: ['Approved by John', 'Recurring monthly expense'],
    },
    {
      name: 'is_recurring',
      label: 'Recurring',
      type: 'boolean',
      description: 'Whether this is a recurring expense',
      examples: ['true', 'false'],
      defaultValue: false,
    },
  ],
};

// Leads Module Configuration
export const leadsConfig: ImportModuleConfig = {
  module: 'leads',
  displayName: 'Sales Leads',
  description: 'Import leads for your sales pipeline',
  tableName: 'leads',
  duplicateKeys: ['email'],
  duplicateDisplayField: 'email',
  templateFileName: 'leads_import_template.csv',
  fields: [
    {
      name: 'email',
      label: 'Email Address',
      type: 'email',
      required: true,
      description: 'Lead\'s email address',
      examples: ['prospect@email.com'],
    },
    {
      name: 'first_name',
      label: 'First Name',
      type: 'string',
      required: true,
      description: 'Lead\'s first name',
      examples: ['Alex', 'Jordan'],
    },
    {
      name: 'last_name',
      label: 'Last Name',
      type: 'string',
      description: 'Lead\'s last name',
      examples: ['Johnson', 'Lee'],
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'phone',
      description: 'Contact phone',
      examples: ['(555) 123-4567'],
    },
    {
      name: 'source',
      label: 'Lead Source',
      type: 'string',
      description: 'How the lead found you',
      examples: ['Website', 'Referral', 'Walk-in', 'Facebook Ad', 'Google'],
    },
    {
      name: 'status',
      label: 'Status',
      type: 'enum',
      enumValues: ['new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost'],
      description: 'Current lead status',
      examples: ['new', 'contacted'],
      defaultValue: 'new',
    },
    {
      name: 'interested_in',
      label: 'Interested In',
      type: 'string',
      description: 'What they\'re interested in',
      examples: ['Personal Training', 'Group Classes', 'Monthly Membership'],
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'string',
      description: 'Additional notes',
      examples: ['Looking to lose weight', 'Price sensitive'],
    },
    {
      name: 'assigned_to',
      label: 'Assigned To (email)',
      type: 'email',
      description: 'Staff member email to assign lead to',
      examples: ['sales@gym.com'],
    },
    {
      name: 'follow_up_date',
      label: 'Follow-up Date',
      type: 'date',
      description: 'Next follow-up date',
      examples: ['2024-02-01'],
    },
  ],
};

// Export all configs
export const moduleConfigs: Record<string, ImportModuleConfig> = {
  members: membersConfig,
  classes: classesConfig,
  staff: staffConfig,
  equipment: equipmentConfig,
  memberships: membershipsConfig,
  expenses: expensesConfig,
  leads: leadsConfig,
};

export function getModuleConfig(module: string): ImportModuleConfig | undefined {
  return moduleConfigs[module];
}

export function getAllModules(): ImportModuleConfig[] {
  return Object.values(moduleConfigs);
}
