import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, FileText, DollarSign, Calendar } from "lucide-react";
import { getSemanticStatusColor } from "@/lib/colorUtils";

interface CorporateInvoice {
  id: string;
  invoice_number: string;
  billing_period_start: string;
  billing_period_end: string;
  member_count: number;
  total_amount: number;
  status: string;
  payment_due_date?: string;
  created_at: string;
  corporate_accounts: {
    company_name: string;
  };
}

export function CorporateInvoiceManager() {
  const { profile } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [selectedCorporateAccount, setSelectedCorporateAccount] = useState("");
  const [billingPeriodStart, setBillingPeriodStart] = useState("");
  const [billingPeriodEnd, setBillingPeriodEnd] = useState("");

  const { data: corporateAccounts } = useQuery({
    queryKey: ['corporate-accounts', profile?.organization_id],
    queryFn: async () => {
      if (!profile?.organization_id) return [];
      
      const { data, error } = await supabase
        .from('corporate_accounts')
        .select('id, company_name, monthly_rate_per_member, billing_cycle')
        .eq('organization_id', profile.organization_id)
        .eq('status', 'active');
      
      if (error) throw error;
      return data;
    },
    enabled: !!profile?.organization_id
  });

  const { data: corporateInvoices, isLoading } = useQuery({
    queryKey: ['corporate-invoices', profile?.organization_id],
    queryFn: async () => {
      if (!profile?.organization_id) return [];
      
      const { data, error } = await supabase
        .from('corporate_invoices')
        .select(`
          *,
          corporate_accounts!corporate_invoices_corporate_account_id_fkey(company_name)
        `)
        .eq('organization_id', profile.organization_id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data;
    },
    enabled: !!profile?.organization_id
  });

  const generateInvoice = useMutation({
    mutationFn: async () => {
      if (!selectedCorporateAccount || !billingPeriodStart || !billingPeriodEnd) {
        throw new Error('Missing required fields');
      }

      // Get corporate account details
      const { data: corporateAccount, error: accountError } = await supabase
        .from('corporate_accounts')
        .select('*')
        .eq('id', selectedCorporateAccount)
        .single();

      if (accountError) throw accountError;

      // Count active members for billing period
      const { count: memberCount, error: countError } = await supabase
        .from('corporate_members')
        .select('*', { count: 'exact' })
        .eq('corporate_account_id', selectedCorporateAccount)
        .eq('is_active', true);

      if (countError) throw countError;

      // Calculate amounts
      const baseAmount = (memberCount || 0) * corporateAccount.monthly_rate_per_member;
      const discountAmount = (baseAmount * (corporateAccount.discount_percentage || 0)) / 100;
      const taxAmount = (baseAmount - discountAmount) * 0.1; // 10% tax
      const totalAmount = baseAmount - discountAmount + taxAmount;

      // Create invoice (invoice_number will be auto-generated by trigger)
      const { data: invoice, error: invoiceError } = await supabase
        .from('corporate_invoices')
        .insert({
          organization_id: profile?.organization_id,
          corporate_account_id: selectedCorporateAccount,
          invoice_number: '', // Will be auto-generated
          billing_period_start: billingPeriodStart,
          billing_period_end: billingPeriodEnd,
          member_count: memberCount || 0,
          base_amount: baseAmount,
          discount_amount: discountAmount,
          tax_amount: taxAmount,
          total_amount: totalAmount,
          payment_due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 30 days from now
          created_by: profile?.id,
          status: 'draft'
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice line items
      await supabase
        .from('corporate_invoice_items')
        .insert({
          invoice_id: invoice.id,
          item_type: 'membership',
          description: `Corporate Membership - ${billingPeriodStart} to ${billingPeriodEnd}`,
          quantity: memberCount || 0,
          unit_price: corporateAccount.monthly_rate_per_member,
          total_price: baseAmount,
          billing_period_start: billingPeriodStart,
          billing_period_end: billingPeriodEnd
        });

      return invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['corporate-invoices'] });
      toast({
        title: "Success",
        description: "Invoice generated successfully",
      });
      setIsDialogOpen(false);
      setSelectedCorporateAccount("");
      setBillingPeriodStart("");
      setBillingPeriodEnd("");
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "Failed to generate invoice",
        variant: "destructive",
      });
    }
  });

  const updateInvoiceStatus = useMutation({
    mutationFn: async ({ invoiceId, status }: { invoiceId: string; status: string }) => {
      const updates: any = { status };
      
      if (status === 'sent') {
        updates.sent_at = new Date().toISOString();
      } else if (status === 'paid') {
        updates.payment_received_date = new Date().toISOString();
      }

      const { error } = await supabase
        .from('corporate_invoices')
        .update(updates)
        .eq('id', invoiceId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['corporate-invoices'] });
      toast({
        title: "Success",
        description: "Invoice status updated",
      });
    }
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    generateInvoice.mutate();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  if (isLoading) return <div>Loading...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Corporate Invoices</h2>
          <p className="text-muted-foreground">Manage corporate billing and invoices</p>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Generate Invoice
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Generate Corporate Invoice</DialogTitle>
              <DialogDescription>
                Create a new invoice for a corporate account
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <Label htmlFor="corporate_account">Corporate Account</Label>
                <Select value={selectedCorporateAccount} onValueChange={setSelectedCorporateAccount} required>
                  <SelectTrigger>
                    <SelectValue placeholder="Select corporate account" />
                  </SelectTrigger>
                  <SelectContent>
                    {corporateAccounts?.map((account) => (
                      <SelectItem key={account.id} value={account.id}>
                        {account.company_name} - ${account.monthly_rate_per_member}/member
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="billing_period_start">Billing Period Start</Label>
                  <Input
                    id="billing_period_start"
                    type="date"
                    value={billingPeriodStart}
                    onChange={(e) => setBillingPeriodStart(e.target.value)}
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="billing_period_end">Billing Period End</Label>
                  <Input
                    id="billing_period_end"
                    type="date"
                    value={billingPeriodEnd}
                    onChange={(e) => setBillingPeriodEnd(e.target.value)}
                    required
                  />
                </div>
              </div>
              
              <div className="flex justify-end space-x-2">
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={generateInvoice.isPending}>
                  {generateInvoice.isPending ? 'Generating...' : 'Generate Invoice'}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <Tabs defaultValue="invoices">
        <TabsList>
          <TabsTrigger value="invoices">Invoices</TabsTrigger>
          <TabsTrigger value="summary">Billing Summary</TabsTrigger>
        </TabsList>
        
        <TabsContent value="invoices">
          <Card>
            <CardHeader>
              <CardTitle>Invoice History</CardTitle>
              <CardDescription>View and manage corporate invoices</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Invoice #</TableHead>
                    <TableHead>Company</TableHead>
                    <TableHead>Billing Period</TableHead>
                    <TableHead>Members</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Due Date</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {corporateInvoices?.map((invoice) => (
                    <TableRow key={invoice.id}>
                      <TableCell className="font-mono">{invoice.invoice_number}</TableCell>
                      <TableCell>{(invoice as any).corporate_accounts?.company_name || 'Unknown'}</TableCell>
                      <TableCell>
                        {new Date(invoice.billing_period_start).toLocaleDateString()} - {new Date(invoice.billing_period_end).toLocaleDateString()}
                      </TableCell>
                      <TableCell>{invoice.member_count}</TableCell>
                      <TableCell>{formatCurrency(invoice.total_amount)}</TableCell>
                      <TableCell>
                        {invoice.payment_due_date ? new Date(invoice.payment_due_date).toLocaleDateString() : '-'}
                      </TableCell>
                      <TableCell>
                        <Badge className={getSemanticStatusColor(invoice.status)}>
                          {invoice.status}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          {invoice.status === 'draft' && (
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => updateInvoiceStatus.mutate({ invoiceId: invoice.id, status: 'sent' })}
                            >
                              Send
                            </Button>
                          )}
                          {invoice.status === 'sent' && (
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => updateInvoiceStatus.mutate({ invoiceId: invoice.id, status: 'paid' })}
                            >
                              Mark Paid
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="summary">
          <div className="grid gap-4 md:grid-cols-3">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Outstanding</CardTitle>
                <DollarSign className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">
                  {formatCurrency(
                    corporateInvoices?.filter(i => ['sent', 'overdue'].includes(i.status))
                      .reduce((sum, i) => sum + i.total_amount, 0) || 0
                  )}
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">This Month</CardTitle>
                <Calendar className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">
                  {formatCurrency(
                    corporateInvoices?.filter(i => {
                      const invoiceDate = new Date(i.created_at);
                      const now = new Date();
                      return invoiceDate.getMonth() === now.getMonth() && invoiceDate.getFullYear() === now.getFullYear();
                    }).reduce((sum, i) => sum + i.total_amount, 0) || 0
                  )}
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Invoices</CardTitle>
                <FileText className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">
                  {corporateInvoices?.length || 0}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}